### ISSUE TITLE
[FIX] render actual single product

### ISSUE THREAD

**Issue by gabrieldefazio** [thetrevlore/Grace-Shopper#16]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

*Issue description here…*

**Comment by emessess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...can view the details for an individual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs](https://trello.com/c/TEfJtDVq/4-can-view-the-details-for-an-individual-product-including-product-descriptions-photos-and-reviews-so-that-i-can-determine-whether)
