### ISSUE TITLE
Cart view and navigation

### ISSUE THREAD

**Issue by e-r-i-k-a** [thetrevlore/Grace-Shopper#21]
Cart view and navigation

**Comment by e-r-i-k-a** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...can view my cart](https://trello.com/c/esB9IwEf/41-can-view-my-cart)

**Comment by e-r-i-k-a** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can navigate to Cart from All Products page](https://trello.com/c/ZGoFuskY/49-can-navigate-to-cart-from-all-products-page)

**Comment by e-r-i-k-a** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can navigate to Cart from Home page](https://trello.com/c/GnaPYo1J/48-can-navigate-to-cart-from-home-page)

**Comment by e-r-i-k-a** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can navigate to Cart from Single Product page](https://trello.com/c/dc34XjwV/50-can-navigate-to-cart-from-single-product-page)

**Comment by emessess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...specify a shipping address and email address when I checkout, so that the items can arrive at the right place](https://trello.com/c/EwZGIILK/11-specify-a-shipping-address-and-email-address-when-i-checkout-so-that-the-items-can-arrive-at-the-right-place)
