### ISSUE TITLE
Fix Order API Routes

### ISSUE THREAD

**Issue by thetrevlore** [thetrevlore/Grace-Shopper#22]

**Comment by thetrevlore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Order API routes](https://trello.com/c/RIdYnkwn/58-fix-order-api-routes)

**Comment by emessess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When a cart is ordered, that order persists to database](https://trello.com/c/n8QwcCjs/53-when-a-cart-is-ordered-that-order-persists-to-database)

**Comment by emessess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes](https://trello.com/c/HlLJ90ax/40-if-a-user-completes-an-order-that-order-should-keep-the-price-of-the-item-at-the-time-when-they-checked-out-even-if-the-price-of)

**Comment by emessess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Orders must contain line items that capture the price, current product ID and quantity](https://trello.com/c/0sTeY7GE/33-orders-must-contain-line-items-that-capture-the-price-current-product-id-and-quantity)

**Comment by gabrieldefazio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...specify a shipping address and email address when I checkout, so that the items can arrive at the right place](https://trello.com/c/EwZGIILK/11-specify-a-shipping-address-and-email-address-when-i-checkout-so-that-the-items-can-arrive-at-the-right-place)

**Comment by gabrieldefazio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...specify a shipping address and email address when I checkout, so that the items can arrive at the right place](https://trello.com/c/EwZGIILK/11-specify-a-shipping-address-and-email-address-when-i-checkout-so-that-the-items-can-arrive-at-the-right-place)

**Comment by gabrieldefazio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [...specify a shipping address and email address when I checkout, so that the items can arrive at the right place](https://trello.com/c/EwZGIILK/11-specify-a-shipping-address-and-email-address-when-i-checkout-so-that-the-items-can-arrive-at-the-right-place)
